version: 2.1

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers

        parameters:
            target:
                type: string
                default: ""

        steps:
            - run:
                name: List variables
                command: echo << parameters.target >> 
                    

workflows:
    build_and_deploy_dev:
        jobs:
            - build:
                target: "hello"
