version: 2.1

commands:
  init_variables:
    description: "Initialize variables"
    parameters:
      target:
        type: string
        default: ""

    steps:
        - run:
            name: Setup shared variables
            command: echo << parameters.target >> 

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers

        parameters:
            target:
                type: string
                default: ""

        steps:
            - run:
                name: List variables
                command: echo << parameters.target >> 
            - init_variables:
                target: "hello2"
                    

workflows:
    build_and_deploy_dev:
        jobs:
            - build:
                target: "hello"
