version: 2.1

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers

        steps:
            - checkout
            - restore_cache:
                keys:
                - dependencies-{{ checksum "package.json" }}

            - run:
                name: Install local dependencies
                command: npm install

            - save_cache:
                key: dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:  
                name: Inject build date
                command: ./scripts/inject-build-date.sh
            
            - run:
                name: Linting
                command: npm run lint
            
            - run:
                name: Testing
                command: npm run test -- --watch=false

            - run:
                name: Building
                command: npm run build -- --prod
            
            - save_cache:
                key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        parameters:
            base_href:
                type: string
                default: ""
            folder:
                type: string
                default: ""
        steps:
            - checkout
            - restore_cache:
                key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Set base href
                command: |
                    echo Base href: <<parameters.base_href>>
                    sed -i.bak 's|.*base href.*|<base href='"<< parameters.base_href >>"'>|' ./dist/index.html
            - run:
                name: Deploy
                command: ./scripts/deploy-to-pages.sh $GH_TOKEN ./dist <<parameters.folder>>
            

workflows:
    build_and_deploy:
        jobs:
            - build
                filters:
                    branches:
                        only: master
            - deploy:
                name: Deploy build
                requires:
                    - build
                filters:
                    branches:
                        only: master
                folder: "builds/$CIRCLE_BUILD_NUM"
                base_href: "/tls-home/builds/$CIRCLE_BUILD_NUM/"
            - deploy:
                name: Deploy latest
                requires:
                    - build
                filters:
                    branches:
                        only: master
                folder: "builds/latest"
                base_href: "/tls-home/builds/latest/"
            - approve:
                type: approval
                requires:
                    - build
                filters:
                    branches:
                        only: master
            - deploy:
                name: Deploy prod
                requires:
                    - approve
                filters:
                    branches:
                        only: master
                folder: "."
                base_href: "/tls-home/"                